baseURL = 'http://dijotm.in/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'm10c'


[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/dijotmathews"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"