baseURL = 'http://dijotm.in/'
languageCode = 'en-us'
title = 'My Musings'
theme = 'm10c'
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3


[params]
  author = "Dijo Mathews"
  title = "Full Stack"
  description = "Some Random Stuff."
  menu_item_separator = " - "


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/dijotmathews"

[params.style]
  darkestColor = "#000000"
  darkColor = "#8f8f8f"
  lightColor = "#f8f8f8"
  lightestColor = "#ffffff"
  primaryColor = "#ffffff"